services:
  mysqlData:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    
    ports:
      - 3307:3306


  be10app:
    image: <namaimagescontainer>
    environment:
      DBusername: "root"
      DBpassword: "12345"
      DBhost: "localhost"
      DBport: 3306
      DBname: "sosmedapps"
      SECRET: "h1d3n"
      SERVERPORT: 8080
    restart: always
    ports:
      - 8000:8080


    