name: Deploy to aws
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/SOSMEDAPPS
            git pull origin main
            docker stop containersosmedapps
            docker rm containersosmedapps
            docker rmi sosmedapp-api
            docker build -t sosmedapp-api:latest .
            docker run -d -p 8080:8080 --name containersosmedapps sosmedapp-api:latest
